"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import VERSION as PYDANTIC_VERSION

if PYDANTIC_VERSION.startswith("1."):
    from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, validator
else:
    from pydantic.v1 import (
        BaseModel,
        Field,
        StrictFloat,
        StrictInt,
        StrictStr,
        validator,
    )


class CreateWorkspaceRequest(BaseModel):
    """
    CreateWorkspaceRequest
    """

    name: StrictStr = Field(...)
    description: StrictStr | None = None
    parent_workspace_id: StrictStr | None = Field(
        default=None, alias="parentWorkspaceId"
    )
    similarity_threshold: StrictFloat | StrictInt | None = Field(
        default=None, alias="similarityThreshold"
    )
    open_ai_temp: StrictFloat | StrictInt | None = Field(
        default=None, alias="openAiTemp"
    )
    open_ai_history: StrictFloat | StrictInt | None = Field(
        default=None, alias="openAiHistory"
    )
    open_ai_prompt: StrictStr | None = Field(default=None, alias="openAiPrompt")
    query_refusal_response: StrictStr | None = Field(
        default=None, alias="queryRefusalResponse"
    )
    chat_mode: StrictStr | None = Field(default=None, alias="chatMode")
    top_n: StrictFloat | StrictInt | None = Field(default=None, alias="topN")
    __properties = [
        "name",
        "description",
        "parentWorkspaceId",
        "similarityThreshold",
        "openAiTemp",
        "openAiHistory",
        "openAiPrompt",
        "queryRefusalResponse",
        "chatMode",
        "topN",
    ]

    @validator("chat_mode")
    def chat_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("chat", "query", "automatic"):
            raise ValueError(
                "must be one of enum values ('chat', 'query', 'automatic')"
            )
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateWorkspaceRequest:
        """Create an instance of CreateWorkspaceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict["description"] = None

        # set to None if parent_workspace_id (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.parent_workspace_id is None
            and "parent_workspace_id" in self.__fields_set__
        ):
            _dict["parentWorkspaceId"] = None

        # set to None if similarity_threshold (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.similarity_threshold is None
            and "similarity_threshold" in self.__fields_set__
        ):
            _dict["similarityThreshold"] = None

        # set to None if open_ai_temp (nullable) is None
        # and __fields_set__ contains the field
        if self.open_ai_temp is None and "open_ai_temp" in self.__fields_set__:
            _dict["openAiTemp"] = None

        # set to None if open_ai_history (nullable) is None
        # and __fields_set__ contains the field
        if self.open_ai_history is None and "open_ai_history" in self.__fields_set__:
            _dict["openAiHistory"] = None

        # set to None if open_ai_prompt (nullable) is None
        # and __fields_set__ contains the field
        if self.open_ai_prompt is None and "open_ai_prompt" in self.__fields_set__:
            _dict["openAiPrompt"] = None

        # set to None if query_refusal_response (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.query_refusal_response is None
            and "query_refusal_response" in self.__fields_set__
        ):
            _dict["queryRefusalResponse"] = None

        # set to None if chat_mode (nullable) is None
        # and __fields_set__ contains the field
        if self.chat_mode is None and "chat_mode" in self.__fields_set__:
            _dict["chatMode"] = None

        # set to None if top_n (nullable) is None
        # and __fields_set__ contains the field
        if self.top_n is None and "top_n" in self.__fields_set__:
            _dict["topN"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateWorkspaceRequest:
        """Create an instance of CreateWorkspaceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateWorkspaceRequest.parse_obj(obj)

        _obj = CreateWorkspaceRequest.parse_obj(
            {
                "name": obj.get("name"),
                "description": obj.get("description"),
                "parent_workspace_id": obj.get("parentWorkspaceId"),
                "similarity_threshold": obj.get("similarityThreshold"),
                "open_ai_temp": obj.get("openAiTemp"),
                "open_ai_history": obj.get("openAiHistory"),
                "open_ai_prompt": obj.get("openAiPrompt"),
                "query_refusal_response": obj.get("queryRefusalResponse"),
                "chat_mode": obj.get("chatMode"),
                "top_n": obj.get("topN"),
            }
        )
        return _obj
