"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import VERSION as PYDANTIC_VERSION

if PYDANTIC_VERSION.startswith("1."):
    from pydantic import BaseModel, Field, conlist

    from anythingllm_client_asyncio.models.workspace_tree_node import WorkspaceTreeNode
else:
    from pydantic.v1 import BaseModel, Field, conlist

    from anythingllm_client_asyncio.models.workspace_tree_node import WorkspaceTreeNode


class GetWorkspaceTreeResponse(BaseModel):
    """
    GetWorkspaceTreeResponse
    """

    tree: conlist(WorkspaceTreeNode) = Field(...)
    __properties = ["tree"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetWorkspaceTreeResponse:
        """Create an instance of GetWorkspaceTreeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in tree (list)
        _items = []
        if self.tree:
            for _item in self.tree:
                if _item:
                    _items.append(_item.to_dict())
            _dict["tree"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetWorkspaceTreeResponse:
        """Create an instance of GetWorkspaceTreeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetWorkspaceTreeResponse.parse_obj(obj)

        _obj = GetWorkspaceTreeResponse.parse_obj(
            {
                "tree": [
                    WorkspaceTreeNode.from_dict(_item) for _item in obj.get("tree")
                ]
                if obj.get("tree") is not None
                else None
            }
        )
        return _obj
