"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import VERSION as PYDANTIC_VERSION

if PYDANTIC_VERSION.startswith("1."):
    from pydantic import BaseModel, StrictStr, conlist
else:
    from pydantic.v1 import BaseModel, StrictStr, conlist


class RemoveDocumentsRequest(BaseModel):
    """
    RemoveDocumentsRequest
    """

    names: conlist(StrictStr) | None = None
    __properties = ["names"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RemoveDocumentsRequest:
        """Create an instance of RemoveDocumentsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RemoveDocumentsRequest:
        """Create an instance of RemoveDocumentsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RemoveDocumentsRequest.parse_obj(obj)

        _obj = RemoveDocumentsRequest.parse_obj({"names": obj.get("names")})
        return _obj
