"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client.api.documents_api import DocumentsApi  # noqa: E501


class TestDocumentsApi:
    """DocumentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_document_folder(self) -> None:
        """Test case for create_document_folder"""
        _api = DocumentsApi()

    def test_get_accepted_file_types(self) -> None:
        """Test case for get_accepted_file_types"""
        _api = DocumentsApi()

    def test_get_document(self) -> None:
        """Test case for get_document"""
        _api = DocumentsApi()

    def test_get_document_metadata_schema(self) -> None:
        """Test case for get_document_metadata_schema"""
        _api = DocumentsApi()

    def test_get_documents_by_folder(self) -> None:
        """Test case for get_documents_by_folder"""
        _api = DocumentsApi()

    def test_list_documents(self) -> None:
        """Test case for list_documents"""
        _api = DocumentsApi()

    def test_move_document_files(self) -> None:
        """Test case for move_document_files"""
        _api = DocumentsApi()

    def test_remove_document_folder(self) -> None:
        """Test case for remove_document_folder"""
        _api = DocumentsApi()

    def test_upload_document(self) -> None:
        """Test case for upload_document"""
        _api = DocumentsApi()

    def test_upload_document_link(self) -> None:
        """Test case for upload_document_link"""
        _api = DocumentsApi()

    def test_upload_document_raw_text(self) -> None:
        """Test case for upload_document_raw_text"""
        _api = DocumentsApi()

    def test_upload_document_to_folder(self) -> None:
        """Test case for upload_document_to_folder"""
        _api = DocumentsApi()
