"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client.models.invalid_api_key import InvalidAPIKey  # noqa: E501

null = None


class TestInvalidAPIKey:
    """InvalidAPIKey unit test stubs"""

    def make_instance(self, include_optional) -> InvalidAPIKey:
        """Test InvalidAPIKey
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        if include_optional:
            return InvalidAPIKey(message="Invalid API Key")
        else:
            return InvalidAPIKey()

    def testInvalidAPIKey(self):
        """Test InvalidAPIKey"""
        _inst_req_only = self.make_instance(include_optional=False)
        _inst_req_and_optional = self.make_instance(include_optional=True)
