"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client.api.workspace_hierarchy_api import (
    WorkspaceHierarchyApi,  # noqa: E501
)


class TestWorkspaceHierarchyApi:
    """WorkspaceHierarchyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspaceHierarchyApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_workspace_breadcrumbs(self) -> None:
        """Test case for get_workspace_breadcrumbs"""
        _api = WorkspaceHierarchyApi()

    def test_get_workspace_children(self) -> None:
        """Test case for get_workspace_children"""
        _api = WorkspaceHierarchyApi()

    def test_get_workspace_subtree(self) -> None:
        """Test case for get_workspace_subtree"""
        _api = WorkspaceHierarchyApi()

    def test_get_workspace_tree(self) -> None:
        """Test case for get_workspace_tree"""
        _api = WorkspaceHierarchyApi()
