"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client.api.admin_api import AdminApi  # noqa: E501


class TestAdminApi:
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_invite(self) -> None:
        """Test case for create_invite"""
        _api = AdminApi()

    def test_create_user(self) -> None:
        """Test case for create_user"""
        _api = AdminApi()

    def test_deactivate_invite(self) -> None:
        """Test case for deactivate_invite"""
        _api = AdminApi()

    def test_delete_user(self) -> None:
        """Test case for delete_user"""
        _api = AdminApi()

    def test_get_workspace_users(self) -> None:
        """Test case for get_workspace_users"""
        _api = AdminApi()

    def test_is_multi_user_mode(self) -> None:
        """Test case for is_multi_user_mode"""
        _api = AdminApi()

    def test_list_invites(self) -> None:
        """Test case for list_invites"""
        _api = AdminApi()

    def test_list_users(self) -> None:
        """Test case for list_users"""
        _api = AdminApi()

    def test_list_workspace_chats(self) -> None:
        """Test case for list_workspace_chats"""
        _api = AdminApi()

    def test_manage_workspace_users(self) -> None:
        """Test case for manage_workspace_users"""
        _api = AdminApi()

    def test_update_admin_preferences(self) -> None:
        """Test case for update_admin_preferences"""
        _api = AdminApi()

    def test_update_user(self) -> None:
        """Test case for update_user"""
        _api = AdminApi()

    def test_update_workspace_users(self) -> None:
        """Test case for update_workspace_users"""
        _api = AdminApi()
