"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client.api.embed_api import EmbedApi  # noqa: E501


class TestEmbedApi:
    """EmbedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmbedApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_embed(self) -> None:
        """Test case for create_embed"""
        _api = EmbedApi()

    def test_delete_embed(self) -> None:
        """Test case for delete_embed"""
        _api = EmbedApi()

    def test_get_embed_chats(self) -> None:
        """Test case for get_embed_chats"""
        _api = EmbedApi()

    def test_get_embed_session_chats(self) -> None:
        """Test case for get_embed_session_chats"""
        _api = EmbedApi()

    def test_list_embeds(self) -> None:
        """Test case for list_embeds"""
        _api = EmbedApi()

    def test_update_embed(self) -> None:
        """Test case for update_embed"""
        _api = EmbedApi()
