"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client.api.workspaces_api import WorkspacesApi  # noqa: E501


class TestWorkspacesApi:
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_chat_with_workspace(self) -> None:
        """Test case for chat_with_workspace"""
        _api = WorkspacesApi()

    def test_create_workspace(self) -> None:
        """Test case for create_workspace"""
        _api = WorkspacesApi()

    def test_delete_workspace(self) -> None:
        """Test case for delete_workspace"""
        _api = WorkspacesApi()

    def test_get_workspace(self) -> None:
        """Test case for get_workspace"""
        _api = WorkspacesApi()

    def test_get_workspace_chats(self) -> None:
        """Test case for get_workspace_chats"""
        _api = WorkspacesApi()

    def test_list_workspaces(self) -> None:
        """Test case for list_workspaces"""
        _api = WorkspacesApi()

    def test_stream_chat_with_workspace(self) -> None:
        """Test case for stream_chat_with_workspace"""
        _api = WorkspacesApi()

    def test_update_workspace(self) -> None:
        """Test case for update_workspace"""
        _api = WorkspacesApi()

    def test_update_workspace_embeddings(self) -> None:
        """Test case for update_workspace_embeddings"""
        _api = WorkspacesApi()

    def test_update_workspace_pin(self) -> None:
        """Test case for update_workspace_pin"""
        _api = WorkspacesApi()

    def test_vector_search_workspace(self) -> None:
        """Test case for vector_search_workspace"""
        _api = WorkspacesApi()
