"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client.api.system_settings_api import SystemSettingsApi  # noqa: E501


class TestSystemSettingsApi:
    """SystemSettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemSettingsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_export_chats(self) -> None:
        """Test case for export_chats"""
        _api = SystemSettingsApi()

    def test_export_environment(self) -> None:
        """Test case for export_environment"""
        _api = SystemSettingsApi()

    def test_get_system_settings(self) -> None:
        """Test case for get_system_settings"""
        _api = SystemSettingsApi()

    def test_get_vector_count(self) -> None:
        """Test case for get_vector_count"""
        _api = SystemSettingsApi()

    def test_remove_documents(self) -> None:
        """Test case for remove_documents"""
        _api = SystemSettingsApi()

    def test_update_system_settings(self) -> None:
        """Test case for update_system_settings"""
        _api = SystemSettingsApi()
