"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client.api.authentication_api import AuthenticationApi  # noqa: E501


class TestAuthenticationApi:
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_verify_auth(self) -> None:
        """Test case for verify_auth"""
        _api = AuthenticationApi()
