"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client.models.get_workspace_children_response import (
    GetWorkspaceChildrenResponse,
)  # noqa: E501

null = None


class TestGetWorkspaceChildrenResponse:
    """GetWorkspaceChildrenResponse unit test stubs"""

    def make_instance(self, include_optional) -> GetWorkspaceChildrenResponse:
        """Test GetWorkspaceChildrenResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        if include_optional:
            return GetWorkspaceChildrenResponse(children=[null])
        else:
            return GetWorkspaceChildrenResponse()

    def testGetWorkspaceChildrenResponse(self):
        """Test GetWorkspaceChildrenResponse"""
        _inst_req_only = self.make_instance(include_optional=False)
        _inst_req_and_optional = self.make_instance(include_optional=True)
