"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client.api.workspace_threads_api import (
    WorkspaceThreadsApi,  # noqa: E501
)


class TestWorkspaceThreadsApi:
    """WorkspaceThreadsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspaceThreadsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_chat_with_thread(self) -> None:
        """Test case for chat_with_thread"""
        _api = WorkspaceThreadsApi()

    def test_create_thread(self) -> None:
        """Test case for create_thread"""
        _api = WorkspaceThreadsApi()

    def test_delete_thread(self) -> None:
        """Test case for delete_thread"""
        _api = WorkspaceThreadsApi()

    def test_get_thread_chats(self) -> None:
        """Test case for get_thread_chats"""
        _api = WorkspaceThreadsApi()

    def test_stream_chat_with_thread(self) -> None:
        """Test case for stream_chat_with_thread"""
        _api = WorkspaceThreadsApi()

    def test_update_thread(self) -> None:
        """Test case for update_thread"""
        _api = WorkspaceThreadsApi()
