"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client.api.open_ai_compatible_endpoints_api import (
    OpenAICompatibleEndpointsApi,
)  # noqa: E501


class TestOpenAICompatibleEndpointsApi:
    """OpenAICompatibleEndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenAICompatibleEndpointsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_openai_chat_completions(self) -> None:
        """Test case for openai_chat_completions"""
        _api = OpenAICompatibleEndpointsApi()

    def test_openai_create_embeddings(self) -> None:
        """Test case for openai_create_embeddings"""
        _api = OpenAICompatibleEndpointsApi()

    def test_openai_list_models(self) -> None:
        """Test case for openai_list_models"""
        _api = OpenAICompatibleEndpointsApi()

    def test_openai_list_vector_stores(self) -> None:
        """Test case for openai_list_vector_stores"""
        _api = OpenAICompatibleEndpointsApi()
