"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import VERSION as PYDANTIC_VERSION

if PYDANTIC_VERSION.startswith("1."):
    from pydantic import BaseModel, Field, StrictStr

    from anythingllm_client.models.workspace import Workspace
else:
    from pydantic.v1 import BaseModel, Field, StrictStr

    from anythingllm_client.models.workspace import Workspace


class UpdateWorkspaceResponse(BaseModel):
    """
    UpdateWorkspaceResponse
    """

    message: StrictStr | None = None
    workspace: Workspace = Field(...)
    __properties = ["message", "workspace"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateWorkspaceResponse:
        """Create an instance of UpdateWorkspaceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of workspace
        if self.workspace:
            _dict["workspace"] = self.workspace.to_dict()
        # set to None if message (nullable) is None
        # and __fields_set__ contains the field
        if self.message is None and "message" in self.__fields_set__:
            _dict["message"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateWorkspaceResponse:
        """Create an instance of UpdateWorkspaceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateWorkspaceResponse.parse_obj(obj)

        _obj = UpdateWorkspaceResponse.parse_obj(
            {
                "message": obj.get("message"),
                "workspace": Workspace.from_dict(obj.get("workspace"))
                if obj.get("workspace") is not None
                else None,
            }
        )
        return _obj
