"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import VERSION as PYDANTIC_VERSION

if PYDANTIC_VERSION.startswith("1."):
    from pydantic import (
        BaseModel,
        Field,
        StrictBool,
        StrictFloat,
        StrictInt,
        StrictStr,
        validator,
    )
else:
    from pydantic.v1 import (
        BaseModel,
        Field,
        StrictBool,
        StrictFloat,
        StrictInt,
        StrictStr,
        validator,
    )


class UpdateWorkspaceRequest(BaseModel):
    """
    UpdateWorkspaceRequest
    """

    name: StrictStr | None = None
    description: StrictStr | None = None
    open_ai_temp: StrictFloat | StrictInt | None = Field(
        default=None, alias="openAiTemp"
    )
    open_ai_history: StrictFloat | StrictInt | None = Field(
        default=None, alias="openAiHistory"
    )
    last_updated_at: StrictStr | None = Field(default=None, alias="lastUpdatedAt")
    open_ai_prompt: StrictStr | None = Field(default=None, alias="openAiPrompt")
    similarity_threshold: StrictFloat | StrictInt | None = Field(
        default=None, alias="similarityThreshold"
    )
    chat_provider: StrictStr | None = Field(default=None, alias="chatProvider")
    chat_model: StrictStr | None = Field(default=None, alias="chatModel")
    top_n: StrictFloat | StrictInt | None = Field(default=None, alias="topN")
    chat_mode: StrictStr | None = Field(default=None, alias="chatMode")
    agent_provider: StrictStr | None = Field(default=None, alias="agentProvider")
    agent_model: StrictStr | None = Field(default=None, alias="agentModel")
    query_refusal_response: StrictStr | None = Field(
        default=None, alias="queryRefusalResponse"
    )
    vector_search_mode: StrictStr | None = Field(default=None, alias="vectorSearchMode")
    include_child_docs: StrictBool | None = Field(
        default=None, alias="includeChildDocs"
    )
    include_ancestor_docs: StrictBool | None = Field(
        default=None, alias="includeAncestorDocs"
    )
    __properties = [
        "name",
        "description",
        "openAiTemp",
        "openAiHistory",
        "lastUpdatedAt",
        "openAiPrompt",
        "similarityThreshold",
        "chatProvider",
        "chatModel",
        "topN",
        "chatMode",
        "agentProvider",
        "agentModel",
        "queryRefusalResponse",
        "vectorSearchMode",
        "includeChildDocs",
        "includeAncestorDocs",
    ]

    @validator("chat_mode")
    def chat_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("chat", "query", "automatic"):
            raise ValueError(
                "must be one of enum values ('chat', 'query', 'automatic')"
            )
        return value

    @validator("vector_search_mode")
    def vector_search_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("default", "rerank"):
            raise ValueError("must be one of enum values ('default', 'rerank')")
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateWorkspaceRequest:
        """Create an instance of UpdateWorkspaceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict["description"] = None

        # set to None if open_ai_temp (nullable) is None
        # and __fields_set__ contains the field
        if self.open_ai_temp is None and "open_ai_temp" in self.__fields_set__:
            _dict["openAiTemp"] = None

        # set to None if open_ai_history (nullable) is None
        # and __fields_set__ contains the field
        if self.open_ai_history is None and "open_ai_history" in self.__fields_set__:
            _dict["openAiHistory"] = None

        # set to None if last_updated_at (nullable) is None
        # and __fields_set__ contains the field
        if self.last_updated_at is None and "last_updated_at" in self.__fields_set__:
            _dict["lastUpdatedAt"] = None

        # set to None if open_ai_prompt (nullable) is None
        # and __fields_set__ contains the field
        if self.open_ai_prompt is None and "open_ai_prompt" in self.__fields_set__:
            _dict["openAiPrompt"] = None

        # set to None if similarity_threshold (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.similarity_threshold is None
            and "similarity_threshold" in self.__fields_set__
        ):
            _dict["similarityThreshold"] = None

        # set to None if chat_provider (nullable) is None
        # and __fields_set__ contains the field
        if self.chat_provider is None and "chat_provider" in self.__fields_set__:
            _dict["chatProvider"] = None

        # set to None if chat_model (nullable) is None
        # and __fields_set__ contains the field
        if self.chat_model is None and "chat_model" in self.__fields_set__:
            _dict["chatModel"] = None

        # set to None if top_n (nullable) is None
        # and __fields_set__ contains the field
        if self.top_n is None and "top_n" in self.__fields_set__:
            _dict["topN"] = None

        # set to None if chat_mode (nullable) is None
        # and __fields_set__ contains the field
        if self.chat_mode is None and "chat_mode" in self.__fields_set__:
            _dict["chatMode"] = None

        # set to None if agent_provider (nullable) is None
        # and __fields_set__ contains the field
        if self.agent_provider is None and "agent_provider" in self.__fields_set__:
            _dict["agentProvider"] = None

        # set to None if agent_model (nullable) is None
        # and __fields_set__ contains the field
        if self.agent_model is None and "agent_model" in self.__fields_set__:
            _dict["agentModel"] = None

        # set to None if query_refusal_response (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.query_refusal_response is None
            and "query_refusal_response" in self.__fields_set__
        ):
            _dict["queryRefusalResponse"] = None

        # set to None if vector_search_mode (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.vector_search_mode is None
            and "vector_search_mode" in self.__fields_set__
        ):
            _dict["vectorSearchMode"] = None

        # set to None if include_child_docs (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.include_child_docs is None
            and "include_child_docs" in self.__fields_set__
        ):
            _dict["includeChildDocs"] = None

        # set to None if include_ancestor_docs (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.include_ancestor_docs is None
            and "include_ancestor_docs" in self.__fields_set__
        ):
            _dict["includeAncestorDocs"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateWorkspaceRequest:
        """Create an instance of UpdateWorkspaceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateWorkspaceRequest.parse_obj(obj)

        _obj = UpdateWorkspaceRequest.parse_obj(
            {
                "name": obj.get("name"),
                "description": obj.get("description"),
                "open_ai_temp": obj.get("openAiTemp"),
                "open_ai_history": obj.get("openAiHistory"),
                "last_updated_at": obj.get("lastUpdatedAt"),
                "open_ai_prompt": obj.get("openAiPrompt"),
                "similarity_threshold": obj.get("similarityThreshold"),
                "chat_provider": obj.get("chatProvider"),
                "chat_model": obj.get("chatModel"),
                "top_n": obj.get("topN"),
                "chat_mode": obj.get("chatMode"),
                "agent_provider": obj.get("agentProvider"),
                "agent_model": obj.get("agentModel"),
                "query_refusal_response": obj.get("queryRefusalResponse"),
                "vector_search_mode": obj.get("vectorSearchMode"),
                "include_child_docs": obj.get("includeChildDocs"),
                "include_ancestor_docs": obj.get("includeAncestorDocs"),
            }
        )
        return _obj
