"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import VERSION as PYDANTIC_VERSION

if PYDANTIC_VERSION.startswith("1."):
    from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr
else:
    from pydantic.v1 import BaseModel, Field, StrictFloat, StrictInt, StrictStr


class UploadDocument200ResponseDocumentsInner(BaseModel):
    """
    UploadDocument200ResponseDocumentsInner
    """

    location: StrictStr | None = None
    name: StrictStr | None = None
    url: StrictStr | None = None
    title: StrictStr | None = None
    doc_author: StrictStr | None = Field(default=None, alias="docAuthor")
    description: StrictStr | None = None
    doc_source: StrictStr | None = Field(default=None, alias="docSource")
    chunk_source: StrictStr | None = Field(default=None, alias="chunkSource")
    published: StrictStr | None = None
    word_count: StrictFloat | StrictInt | None = Field(default=None, alias="wordCount")
    token_count_estimate: StrictFloat | StrictInt | None = None
    __properties = [
        "location",
        "name",
        "url",
        "title",
        "docAuthor",
        "description",
        "docSource",
        "chunkSource",
        "published",
        "wordCount",
        "token_count_estimate",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UploadDocument200ResponseDocumentsInner:
        """Create an instance of UploadDocument200ResponseDocumentsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UploadDocument200ResponseDocumentsInner:
        """Create an instance of UploadDocument200ResponseDocumentsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UploadDocument200ResponseDocumentsInner.parse_obj(obj)

        _obj = UploadDocument200ResponseDocumentsInner.parse_obj(
            {
                "location": obj.get("location"),
                "name": obj.get("name"),
                "url": obj.get("url"),
                "title": obj.get("title"),
                "doc_author": obj.get("docAuthor"),
                "description": obj.get("description"),
                "doc_source": obj.get("docSource"),
                "chunk_source": obj.get("chunkSource"),
                "published": obj.get("published"),
                "word_count": obj.get("wordCount"),
                "token_count_estimate": obj.get("token_count_estimate"),
            }
        )
        return _obj
