"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import pytest

from anythingllm_client_asyncio.api.user_management_api import (
    UserManagementApi,  # noqa: E501
)

pytestmark = pytest.mark.anyio


@pytest.fixture(scope="session")
def anyio_backend():
    return "asyncio"


class TestUserManagementApi:
    """UserManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserManagementApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    async def test_get_user_management_list(self) -> None:
        """Test case for get_user_management_list"""
        _api = UserManagementApi()

    async def test_issue_auth_token(self) -> None:
        """Test case for issue_auth_token"""
        _api = UserManagementApi()
