"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import anythingllm_client_asyncio.models
from anythingllm_client_asyncio.models.upload_document200_response import (
    UploadDocument200Response,
)  # noqa: E501

null = None


class TestUploadDocument200Response:
    """UploadDocument200Response unit test stubs"""

    def make_instance(self, include_optional) -> UploadDocument200Response:
        """Test UploadDocument200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        if include_optional:
            return UploadDocument200Response(
                success=True,
                error="",
                documents=[
                    anythingllm_client_asyncio.models.upload_document_200_response_documents_inner.uploadDocument_200_response_documents_inner(
                        location="",
                        name="",
                        url="",
                        title="",
                        doc_author="",
                        description="",
                        doc_source="",
                        chunk_source="",
                        published="",
                        word_count=1.337,
                        token_count_estimate=1.337,
                    )
                ],
            )
        else:
            return UploadDocument200Response()

    def testUploadDocument200Response(self):
        """Test UploadDocument200Response"""
        _inst_req_only = self.make_instance(include_optional=False)
        _inst_req_and_optional = self.make_instance(include_optional=True)
