"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import pytest

from anythingllm_client_asyncio.api.authentication_api import (
    AuthenticationApi,  # noqa: E501
)

pytestmark = pytest.mark.anyio


@pytest.fixture(scope="session")
def anyio_backend():
    return "asyncio"


class TestAuthenticationApi:
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    async def test_verify_auth(self) -> None:
        """Test case for verify_auth"""
        _api = AuthenticationApi()
