"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client_asyncio.models.create_workspace_request import (
    CreateWorkspaceRequest,
)  # noqa: E501

null = None


class TestCreateWorkspaceRequest:
    """CreateWorkspaceRequest unit test stubs"""

    def make_instance(self, include_optional) -> CreateWorkspaceRequest:
        """Test CreateWorkspaceRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        if include_optional:
            return CreateWorkspaceRequest(
                name="My New Workspace",
                parent_workspace_id="",
                similarity_threshold=1.337,
                open_ai_temp=1.337,
                open_ai_history=1.337,
                open_ai_prompt="",
                query_refusal_response="",
                chat_mode="chat",
                top_n=1.337,
            )
        else:
            return CreateWorkspaceRequest(
                name="My New Workspace",
            )

    def testCreateWorkspaceRequest(self):
        """Test CreateWorkspaceRequest"""
        _inst_req_only = self.make_instance(include_optional=False)
        _inst_req_and_optional = self.make_instance(include_optional=True)
