"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client_asyncio.models.upload_document200_response_documents_inner import (
    UploadDocument200ResponseDocumentsInner,
)  # noqa: E501

null = None


class TestUploadDocument200ResponseDocumentsInner:
    """UploadDocument200ResponseDocumentsInner unit test stubs"""

    def make_instance(
        self, include_optional
    ) -> UploadDocument200ResponseDocumentsInner:
        """Test UploadDocument200ResponseDocumentsInner
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        if include_optional:
            return UploadDocument200ResponseDocumentsInner(
                location="",
                name="",
                url="",
                title="",
                doc_author="",
                description="",
                doc_source="",
                chunk_source="",
                published="",
                word_count=1.337,
                token_count_estimate=1.337,
            )
        else:
            return UploadDocument200ResponseDocumentsInner()

    def testUploadDocument200ResponseDocumentsInner(self):
        """Test UploadDocument200ResponseDocumentsInner"""
        _inst_req_only = self.make_instance(include_optional=False)
        _inst_req_and_optional = self.make_instance(include_optional=True)
