"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import anythingllm_client_asyncio.models
from anythingllm_client_asyncio.models.list_workspaces_response import (
    ListWorkspacesResponse,
)  # noqa: E501

null = None


class TestListWorkspacesResponse:
    """ListWorkspacesResponse unit test stubs"""

    def make_instance(self, include_optional) -> ListWorkspacesResponse:
        """Test ListWorkspacesResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        if include_optional:
            return ListWorkspacesResponse(
                workspaces=[
                    anythingllm_client_asyncio.models.workspace.Workspace(
                        id=1,
                        name="string",
                        slug="string",
                        vector_tag="string",
                        created_at="2024-01-01T00:00:00.000Z",
                        open_ai_temp=0.7,
                        open_ai_history=0,
                        last_updated_at="2024-01-01T00:00:00.000Z",
                        open_ai_prompt="string",
                        similarity_threshold=0.7,
                        chat_provider="",
                        chat_model="",
                        top_n=1.337,
                        chat_mode="chat",
                        pfp_filename="",
                        agent_provider="",
                        agent_model="gpt-4",
                        query_refusal_response="string",
                        vector_search_mode="default",
                        parent_workspace_id=1,
                        path="",
                        depth=1.337,
                        include_child_docs=False,
                        include_ancestor_docs=False,
                    )
                ]
            )
        else:
            return ListWorkspacesResponse()

    def testListWorkspacesResponse(self):
        """Test ListWorkspacesResponse"""
        _inst_req_only = self.make_instance(include_optional=False)
        _inst_req_and_optional = self.make_instance(include_optional=True)
