"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from anythingllm_client_asyncio.models.update_workspace_request import (
    UpdateWorkspaceRequest,
)  # noqa: E501

null = None


class TestUpdateWorkspaceRequest:
    """UpdateWorkspaceRequest unit test stubs"""

    def make_instance(self, include_optional) -> UpdateWorkspaceRequest:
        """Test UpdateWorkspaceRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        if include_optional:
            return UpdateWorkspaceRequest(
                name="string",
                description="A workspace for research documents",
                open_ai_temp=0.7,
                open_ai_history=0,
                last_updated_at="2024-01-01T00:00:00.000Z",
                open_ai_prompt="string",
                similarity_threshold=0.7,
                chat_provider="",
                chat_model="",
                top_n=1.337,
                chat_mode="chat",
                agent_provider="",
                agent_model="gpt-4",
                query_refusal_response="string",
                vector_search_mode="default",
                include_child_docs=False,
                include_ancestor_docs=False,
            )
        else:
            return UpdateWorkspaceRequest()

    def testUpdateWorkspaceRequest(self):
        """Test UpdateWorkspaceRequest"""
        _inst_req_only = self.make_instance(include_optional=False)
        _inst_req_and_optional = self.make_instance(include_optional=True)
