"""
AnythingLLM Developer API

API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import re  # noqa: F401

from pydantic import VERSION as PYDANTIC_VERSION

if PYDANTIC_VERSION.startswith("1."):
    from pydantic import validate_arguments
else:
    from pydantic.v1 import validate_arguments

from typing import Annotated

from pydantic import Field, StrictStr

from anythingllm_client_asyncio.api_client import ApiClient
from anythingllm_client_asyncio.api_response import ApiResponse
from anythingllm_client_asyncio.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError,
)


class WorkspaceThreadsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    async def chat_with_thread(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        thread_slug: Annotated[
            StrictStr, Field(..., description="Unique slug of thread")
        ],
        **kwargs,
    ) -> object:  # noqa: E501
        """chat_with_thread  # noqa: E501

        Chat with a workspace thread  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param thread_slug: Unique slug of thread (required)
        :type thread_slug: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: object
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the chat_with_thread_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.chat_with_thread_with_http_info(slug, thread_slug, **kwargs)  # noqa: E501

    @validate_arguments
    async def chat_with_thread_with_http_info(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        thread_slug: Annotated[
            StrictStr, Field(..., description="Unique slug of thread")
        ],
        **kwargs,
    ) -> ApiResponse:  # noqa: E501
        """chat_with_thread  # noqa: E501

        Chat with a workspace thread  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param thread_slug: Unique slug of thread (required)
        :type thread_slug: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(object, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = ["slug", "thread_slug"]
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{_key}'"
                    " to method chat_with_thread"
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params["slug"] is not None:
            _path_params["slug"] = _params["slug"]

        if _params["thread_slug"] is not None:
            _path_params["threadSlug"] = _params["thread_slug"]

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json", "application/xml"]
        )  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get(
            "_content_type",
            self.api_client.select_header_content_type(["application/json"]),
        )
        if _content_types_list:
            _header_params["Content-Type"] = _content_types_list

        # authentication setting
        _auth_settings = ["BearerAuth"]  # noqa: E501

        _response_types_map = {
            "200": "object",
            "400": None,
            "403": "InvalidAPIKey",
            "500": None,
        }

        return await self.api_client.call_api(
            "/v1/workspace/{slug}/thread/{threadSlug}/chat",
            "POST",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    @validate_arguments
    async def create_thread(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        **kwargs,
    ) -> object:  # noqa: E501
        """create_thread  # noqa: E501

        Create a new workspace thread  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: object
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the create_thread_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.create_thread_with_http_info(slug, **kwargs)  # noqa: E501

    @validate_arguments
    async def create_thread_with_http_info(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        **kwargs,
    ) -> ApiResponse:  # noqa: E501
        """create_thread  # noqa: E501

        Create a new workspace thread  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(object, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = ["slug"]
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{_key}'"
                    " to method create_thread"
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params["slug"] is not None:
            _path_params["slug"] = _params["slug"]

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json", "application/xml"]
        )  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get(
            "_content_type",
            self.api_client.select_header_content_type(["application/json"]),
        )
        if _content_types_list:
            _header_params["Content-Type"] = _content_types_list

        # authentication setting
        _auth_settings = ["BearerAuth"]  # noqa: E501

        _response_types_map = {
            "200": "object",
            "400": None,
            "403": "InvalidAPIKey",
            "500": None,
        }

        return await self.api_client.call_api(
            "/v1/workspace/{slug}/thread/new",
            "POST",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    @validate_arguments
    async def delete_thread(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        thread_slug: Annotated[
            StrictStr, Field(..., description="Unique slug of thread")
        ],
        **kwargs,
    ) -> None:  # noqa: E501
        """delete_thread  # noqa: E501

        Delete a workspace thread  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param thread_slug: Unique slug of thread (required)
        :type thread_slug: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the delete_thread_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.delete_thread_with_http_info(slug, thread_slug, **kwargs)  # noqa: E501

    @validate_arguments
    async def delete_thread_with_http_info(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        thread_slug: Annotated[
            StrictStr, Field(..., description="Unique slug of thread")
        ],
        **kwargs,
    ) -> ApiResponse:  # noqa: E501
        """delete_thread  # noqa: E501

        Delete a workspace thread  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param thread_slug: Unique slug of thread (required)
        :type thread_slug: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        _params = locals()

        _all_params = ["slug", "thread_slug"]
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{_key}'"
                    " to method delete_thread"
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params["slug"] is not None:
            _path_params["slug"] = _params["slug"]

        if _params["thread_slug"] is not None:
            _path_params["threadSlug"] = _params["thread_slug"]

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json", "application/xml"]
        )  # noqa: E501

        # authentication setting
        _auth_settings = ["BearerAuth"]  # noqa: E501

        _response_types_map = {}

        return await self.api_client.call_api(
            "/v1/workspace/{slug}/thread/{threadSlug}",
            "DELETE",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    @validate_arguments
    async def get_thread_chats(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        thread_slug: Annotated[
            StrictStr, Field(..., description="Unique slug of thread")
        ],
        **kwargs,
    ) -> object:  # noqa: E501
        """get_thread_chats  # noqa: E501

        Get chats for a workspace thread  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param thread_slug: Unique slug of thread (required)
        :type thread_slug: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: object
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the get_thread_chats_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.get_thread_chats_with_http_info(slug, thread_slug, **kwargs)  # noqa: E501

    @validate_arguments
    async def get_thread_chats_with_http_info(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        thread_slug: Annotated[
            StrictStr, Field(..., description="Unique slug of thread")
        ],
        **kwargs,
    ) -> ApiResponse:  # noqa: E501
        """get_thread_chats  # noqa: E501

        Get chats for a workspace thread  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param thread_slug: Unique slug of thread (required)
        :type thread_slug: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(object, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = ["slug", "thread_slug"]
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{_key}'"
                    " to method get_thread_chats"
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params["slug"] is not None:
            _path_params["slug"] = _params["slug"]

        if _params["thread_slug"] is not None:
            _path_params["threadSlug"] = _params["thread_slug"]

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json", "application/xml"]
        )  # noqa: E501

        # authentication setting
        _auth_settings = ["BearerAuth"]  # noqa: E501

        _response_types_map = {
            "200": "object",
            "400": None,
            "403": "InvalidAPIKey",
            "500": None,
        }

        return await self.api_client.call_api(
            "/v1/workspace/{slug}/thread/{threadSlug}/chats",
            "GET",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    @validate_arguments
    async def stream_chat_with_thread(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        thread_slug: Annotated[
            StrictStr, Field(..., description="Unique slug of thread")
        ],
        **kwargs,
    ) -> list[str]:  # noqa: E501
        """stream_chat_with_thread  # noqa: E501

        Stream chat with a workspace thread  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param thread_slug: Unique slug of thread (required)
        :type thread_slug: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[str]
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the stream_chat_with_thread_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.stream_chat_with_thread_with_http_info(
            slug, thread_slug, **kwargs
        )  # noqa: E501

    @validate_arguments
    async def stream_chat_with_thread_with_http_info(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        thread_slug: Annotated[
            StrictStr, Field(..., description="Unique slug of thread")
        ],
        **kwargs,
    ) -> ApiResponse:  # noqa: E501
        """stream_chat_with_thread  # noqa: E501

        Stream chat with a workspace thread  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param thread_slug: Unique slug of thread (required)
        :type thread_slug: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[str], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = ["slug", "thread_slug"]
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{_key}'"
                    " to method stream_chat_with_thread"
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params["slug"] is not None:
            _path_params["slug"] = _params["slug"]

        if _params["thread_slug"] is not None:
            _path_params["threadSlug"] = _params["thread_slug"]

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["text/event-stream", "application/json", "application/xml"]
        )  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get(
            "_content_type",
            self.api_client.select_header_content_type(["application/json"]),
        )
        if _content_types_list:
            _header_params["Content-Type"] = _content_types_list

        # authentication setting
        _auth_settings = ["BearerAuth"]  # noqa: E501

        _response_types_map = {
            "200": "List[str]",
            "400": None,
            "403": "InvalidAPIKey",
        }

        return await self.api_client.call_api(
            "/v1/workspace/{slug}/thread/{threadSlug}/stream-chat",
            "POST",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    @validate_arguments
    async def update_thread(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        thread_slug: Annotated[
            StrictStr, Field(..., description="Unique slug of thread")
        ],
        **kwargs,
    ) -> object:  # noqa: E501
        """update_thread  # noqa: E501

        Update thread name by its unique slug.  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param thread_slug: Unique slug of thread (required)
        :type thread_slug: str
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: object
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the update_thread_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return await self.update_thread_with_http_info(slug, thread_slug, **kwargs)  # noqa: E501

    @validate_arguments
    async def update_thread_with_http_info(
        self,
        slug: Annotated[StrictStr, Field(..., description="Unique slug of workspace")],
        thread_slug: Annotated[
            StrictStr, Field(..., description="Unique slug of thread")
        ],
        **kwargs,
    ) -> ApiResponse:  # noqa: E501
        """update_thread  # noqa: E501

        Update thread name by its unique slug.  # noqa: E501

        :param slug: Unique slug of workspace (required)
        :type slug: str
        :param thread_slug: Unique slug of thread (required)
        :type thread_slug: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(object, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = ["slug", "thread_slug"]
        _all_params.extend(
            [
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{_key}'"
                    " to method update_thread"
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params["slug"] is not None:
            _path_params["slug"] = _params["slug"]

        if _params["thread_slug"] is not None:
            _path_params["threadSlug"] = _params["thread_slug"]

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json", "application/xml"]
        )  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get(
            "_content_type",
            self.api_client.select_header_content_type(["application/json"]),
        )
        if _content_types_list:
            _header_params["Content-Type"] = _content_types_list

        # authentication setting
        _auth_settings = ["BearerAuth"]  # noqa: E501

        _response_types_map = {
            "200": "object",
            "400": None,
            "403": "InvalidAPIKey",
            "500": None,
        }

        return await self.api_client.call_api(
            "/v1/workspace/{slug}/thread/{threadSlug}/update",
            "POST",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )
